name: Testing web and api
# Comment
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  selenium_python_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this page
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Chrome
        run: sudo apt-get install -y chromium-browser
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set API Key
        run: echo "export API_KEY=$API_KEY" >> $GITHUB_ENV
      - name: Run tests
        run: pytest --headless
      - name: Save HTML report as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Test-Report
          path: ./src/results/report.html